version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    hostname: mariadb
    container_name: mariadb
    volumes:
      - mc1_db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db_mc1
      MARIADB_USER: admin
      MARIADB_PASSWORD: password

  mc1:
    build: https://github.com/sidalsoft/mc1.git
    image: mc1:latest
    hostname: mc1
    container_name: mc1
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/db_mc1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MY_INTERACTION_INTERVAL: 10

  mc2:
    build: https://github.com/sidalsoft/mc2.git
    image: mc2:latest
    hostname: mc2
    container_name: mc2
    ports:
      - "8081:8080"
    restart: on-failure
    depends_on:
      - kafka
      - mc1
    links:
      - mc1
    environment:
      MY_WEB_SOCKET_URL: ws://mc1:8080/messages
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      MY_KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      MY_KAFKA_TOPIC: message

  mc3:
    build: https://github.com/sidalsoft/mc3.git
    image: mc3:latest
    hostname: mc3
    container_name: mc3
    ports:
      - "8082:8080"
    restart: on-failure
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      MY_KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      MY_KAFKA_TOPIC: message
      MY_MC1_HOST: mc1

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    volumes:
      - "zookeeper_data:/bitnami"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=message

volumes:
  mc1_db_data:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local